# This workflow will push and update articles on dev.to each time a new
# commit is pushed to the main branch.
#
# To make it work, you need a dev.to API key, see:
# https://developers.forem.com/api/#section/Authentication/api_key
#
# Once you have generated the token, you need to add them as a secret in your
# GitHub repository:
# - DEVTO_TOKEN: your dev.to API key
# See https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets
# for more information about GitHub secrets.

name: publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}  # Ensure the checkout action uses the PAT

    - name: Publish articles on dev.to
      uses: sinedied/publish-devto@v2
      with:
        devto_key: ${{ secrets.DEVTO_TOKEN }}
        github_token: ${{ secrets.GH_TOKEN }}  # Ensure this step uses PAT
        files: 'posts/**/*.md'
        branch: main
        conventional_commits: true
        dry_run: ${{ github.event_name == 'pull_request' }}

    - name: Configure user for commit
      run: |
        git config --global user.name "airtoncarneiro"
        git config --global user.email "airtoncarneiro@gmail.com"

    - uses: actions-ecosystem/action-create-comment@v1
      if: ${{ github.event_name == 'pull_request' }}
      with:
        github_token: ${{ secrets.GH_TOKEN }}  # Use PAT for commenting as well
        body: |
          Changes result:
          ```
          ${{ steps.publish_devto.outputs.result_summary }}
          ```
